Repository TEAM-DAWM/SHELLIN-CLIENT, pull requests merged in 2024-11, with the labels that each got.

#285 [INIT] theme 색상 & 폰트 설정
  src/styles/color.ts
  src/styles/font.ts
  src/styles/theme.ts
Labels: 🫧 지민, 🔧 초기세팅

#288 [FEAT] 공통 컴포넌트 버튼 퍼블리싱
  src/assets/svg/index.ts
  src/components/common/NavBarIcon.tsx
  src/components/common/v2/Button.tsx
  src/stories/Common/Button/Button.stories.tsx
Labels: 😻 승연, 🖼️ 뷰 퍼블리싱, v2

#295 [DOCS] 스토리북 배포
  .github/workflows/chromatic.yml
  package.json
  yarn.lock
Labels: 😻 승연, 배포

#293 [FEAT] 공통 컴포넌트 컨트롤버튼 퍼블리싱
  src/components/common/v2/button/Button.tsx
  src/components/common/v2/control/CheckButton.tsx
  src/components/common/v2/control/DropdownButton.tsx
  src/components/common/v2/control/ToggleLabelButton.tsx
  src/components/common/v2/control/ToggleSwitchButton.tsx
  src/stories/Common/Button/Button.stories.tsx
  src/stories/Common/Button/CheckButton.stories.tsx
  src/stories/Common/Button/DropdownButton.stories.ts
  src/stories/Common/Button/ToggleLabelButton.stories.ts
  src/stories/Common/Button/ToggleSwitchButton.stories.ts
  src/styles/shadow.ts
  src/styles/theme.ts
Labels: 😻 승연, 🖼️ 뷰 퍼블리싱, v2

#303 [STYLE] add color token
  src/styles/colorToken.ts
  src/styles/font.ts
  src/styles/theme.ts
Labels: 🍀 지원, 🔧 초기세팅, v2

#305 [FIX] 기존 공통 컴포넌트 아이콘 수정
  src/components/common/v2/IconButton.tsx
  src/components/common/v2/button/Button.tsx
  src/components/common/v2/control/CheckButton.tsx
  src/components/common/v2/control/DropdownButton.tsx
  src/stories/Common/Button/Button.stories.tsx
  src/stories/Common/Button/IconButton.stories.tsx
Labels: 😻 승연, v2
