Repository TEAM-DAWM/SHELLIN-CLIENT, pull requests merged in 2024-06, with the labels that each got.

#5 [INIT] issue, pr 템플릿 추가
  .github/ISSUE_TEMPLATE/기능-요청-이슈.md
  .github/ISSUE_TEMPLATE/버그-리포트-이슈.md
  .github/pull_request_template.md
Labels: 😻 승연, 🔧 초기세팅

#2 [INIT] 프로젝트 생성 및 stylelint, global style 적용 #1
  .eslintrc.cjs
  .gitignore
  .stylelintrc
  index.html
  package.json
  src/App.tsx
  src/main.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: 🏰 성희, 🔧 초기세팅

#8 [INIT] svgr 설정
  package.json
  public/svg/ic_circle-arrow-right-solid.svg
  public/svg/index.ts
  src/App.tsx
  src/assets/svg.d.ts
  src/assets/svg/index.ts
  src/vite-env.d.ts
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: 🍀 지원, 🔧 초기세팅

#9 [INIT] eslint & prettier 초기세팅
  .eslintrc.cjs
  .prettierrc
  package.json
  src/App.tsx
  yarn.lock
Labels: 🫧 지민, 🔧 초기세팅
