Repository TEAM-DAWM/SHELLIN-CLIENT, pull requests merged in 2024-07, with the labels that each got.

#11 [FIX] update yarn checksums
  yarn.lock
Labels: 😻 승연, 에러 수정

#14 [FIX] stylelint rem 단위 추가
  .stylelintrc
Labels: 🫧 지민, 🔧 초기세팅

#16 [FIX] 배포 Integrity check fail
  yarn.lock
Labels: 😻 승연, 에러 수정, 배포

#20 [FEAT] theme 색상, 폰트 설정
  .eslintrc.cjs
  .stylelintrc
  src/App.tsx
  src/main.tsx
  src/styles/GlobalStyle.tsx
  src/styles/emotion.d.ts
  src/styles/font.css
  src/styles/theme.ts
Labels: 🏰 성희, 🔧 초기세팅

#25 [ INIT] 라우팅 설정
  package.json
  src/App.tsx
  src/Router.tsx
  src/pages/Calendar.tsx
  src/pages/DashBoard.tsx
  src/pages/Login.tsx
  src/pages/NotFound.tsx
  src/pages/Setting.tsx
  src/pages/Today.tsx
  yarn.lock
Labels: 😻 승연, 🔧 초기세팅

#19 [BUILD] CI/CD 구성
  .github/workflows/gradle.yaml
Labels: 🍀 지원, 배포

#28 [INIT] storybook 초기 세팅
  .eslintrc.cjs
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  src/stories/Button/Button.stories.ts
  src/stories/Button/Button.tsx
  src/stories/Button/buttonStyle.ts
  src/stories/Configure.mdx
  tsconfig.app.json
  yarn.lock
Labels: 🏰 성희, 🔧 초기세팅

#30 [FEAT] 텍스트박스 공통컴포넌트 퍼블리싱
  src/assets/svg/arrow-narrow-right.svg
  src/assets/svg/icn_clock.svg
  src/assets/svg/index.ts
  src/components/common/textbox/TextInputDesc.tsx
  src/components/common/textbox/TextInputStaging.tsx
  src/components/common/textbox/TextInputTime.tsx
  src/components/common/textbox/TextInputTitle.tsx
  src/components/common/textbox/TextboxDailydate.tsx
  src/components/common/textbox/TextboxInput.tsx
  src/pages/Today.tsx
  src/types/textInputType.ts
  src/utils/getNameOfDay.ts
  yarn.lock
Labels: 😻 승연, 🖼️ 뷰 퍼블리싱

#34 [FIX] develop에 PR 시 action 스킵되는 오류 수정
  .github/workflows/gradle.yaml
  src/components/common/textbox/TextInputStaging.tsx
  src/pages/Calendar.tsx
  src/pages/DashBoard.tsx
  src/pages/Login.tsx
  src/pages/Setting.tsx
  src/pages/Today.tsx
Labels: 🍀 지원, 🔧 초기세팅, 에러 수정

#36 [FEAT] 네비바 퍼블리싱
  .github/workflows/gradle.yaml
  .stylelintrc
  src/Router.tsx
  src/assets/images/sample.png
  src/assets/svg/icn_nav_calendar.svg
  src/assets/svg/icn_nav_dashboard.svg
  src/assets/svg/icn_nav_setting.svg
  src/assets/svg/icn_nav_today.svg
  src/assets/svg/index.ts
  src/components/common/NavBar.tsx
  src/components/common/NavBarIcon.tsx
  src/constants/pages.ts
  src/pages/Calendar.tsx
  src/pages/DashBoard.tsx
  src/pages/Login.tsx
  src/pages/MainLayout.tsx
  src/pages/Setting.tsx
  src/pages/Today.tsx
  src/styles/theme.ts
Labels: 😻 승연, 🖼️ 뷰 퍼블리싱, ⭐️ 기능 추가

#41 [BUG] eslint 오류 해결
  .eslintrc.cjs
  .prettierrc
  index.html
  package.json
  public/svg/ic_circle-arrow-right-solid.svg
  public/svg/index.ts
  src/Router.tsx
  src/assets/svg.d.ts
  src/components/common/NavBar.tsx
  src/components/common/NavBarIcon.tsx
  src/components/common/textbox/TextInputDesc.tsx
  src/components/common/textbox/TextInputStaging.tsx
  src/components/common/textbox/TextInputTime.tsx
  src/components/common/textbox/TextInputTitle.tsx
  src/components/common/textbox/TextboxDailydate.tsx
  src/components/common/textbox/TextboxInput.tsx
  src/main.tsx
  src/pages/Calendar.tsx
  src/pages/DashBoard.tsx
  src/pages/Login.tsx
  src/pages/MainLayout.tsx
  src/pages/NotFound.tsx
  src/pages/Setting.tsx
  src/pages/Today.tsx
  src/stories/Button/Button.stories.ts
  src/stories/Button/Button.tsx
  src/stories/Button/buttonStyle.ts
  src/styles/theme.ts
  src/utils/getNameOfDay.ts
  tsconfig.node.json
  yarn.lock
Labels: 😻 승연, 에러 수정

#38 [FEAT] 공통 모달 퍼블리싱
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalHeaderBtn.tsx
  src/components/common/modal/ModalTextInputTime.tsx
  src/components/common/modal/TextInputBox.tsx
  src/components/common/textbox/TextInputDesc.tsx
  src/components/common/textbox/TextInputTime.tsx
  src/components/common/textbox/TextInputTitle.tsx
Labels: 🏰 성희, 🖼️ 뷰 퍼블리싱

#39 [FEAT] 마감기한 공통컴포넌트 퍼블리싱
  package.json
  src/assets/svg/calendar-minus-01.svg
  src/assets/svg/clock.svg
  src/assets/svg/index.ts
  src/assets/svg/line164.svg
  src/assets/svg/x-circle.svg
  src/components/common/BtnDate/BtnDate.tsx
  src/components/common/BtnDate/BtnDateText.tsx
  src/components/common/BtnDate/BtnStagingDate.tsx
  src/pages/Today.tsx
  src/styles/theme.ts
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱

#46 [FEAT] theme button 색상값 적용
  src/styles/theme.ts
Labels: 🫧 지민, 🔧 초기세팅

#40 [FEAT] 공통 컴포넌트 버튼 퍼블리싱
  src/assets/svg/Delete.svg
  src/assets/svg/DoneIcon.svg
  src/assets/svg/PlusArrow.svg
  src/assets/svg/ProgressIcon.svg
  src/assets/svg/Selectbox_Selected.svg
  src/assets/svg/Selectbox_Unselected.svg
  src/assets/svg/SettingCheck1.svg
  src/assets/svg/SettingCheck2Icon.svg
  src/assets/svg/SettingCheck3Icon.svg
  src/assets/svg/SettingProgressIcon.svg
  src/assets/svg/SettingXIcon.svg
  src/assets/svg/arrow-up.svg
  src/assets/svg/ic_delete.svg
  src/assets/svg/index.ts
  src/assets/svg/refresh.svg
  src/components/common/button/ArrangeBtn.tsx
  src/components/common/button/Check1Btn.tsx
  src/components/common/button/DeleteBtn.tsx
  src/components/common/button/DeleteCancelBtn.tsx
  src/components/common/button/EnterBtn.tsx
  src/components/common/button/OkayCancelBtn.tsx
  src/components/common/button/ProgressBtn.tsx
  src/components/common/button/RefreshBtn.tsx
  src/components/common/button/SettingCheck2Btn.tsx
  src/components/common/button/SettingCheck3Btn.tsx
  src/components/common/button/SettingDeleteBtn.tsx
  src/components/common/button/SettingXBtn.tsx
  src/components/common/button/StatusDoneBtn.tsx
  src/components/common/button/StatusInProgressBtn.tsx
  src/components/common/button/StatusStagingBtn.tsx
  src/components/common/button/StatusTodoBtn.tsx
  src/components/common/button/TextBtn.tsx
  src/components/common/button/TimelineDeleteBtn.tsx
  src/components/common/button/TodayPlusBtn.tsx
  src/pages/Setting.tsx
  src/styles/GlobalStyle.tsx
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱

#51 [BUG] vercel.json 추가
  vercel.json
Labels: 😻 승연, 배포

#48 [FEAT] Arrange 버튼 퍼블리싱
  .eslintrc.cjs
  src/assets/svg/icn_arrange_calendar.svg
  src/assets/svg/icn_arrange_left.svg
  src/assets/svg/icn_arrange_right.svg
  src/assets/svg/icn_arrange_set.svg
  src/assets/svg/index.ts
  src/components/common/NavBar.tsx
  src/components/common/arrangeBtn/ArrangeBtn.tsx
  src/components/common/arrangeBtn/arrangeBtnStyle.ts
  src/pages/Calendar.tsx
  src/pages/DashBoard.tsx
  src/pages/MainLayout.tsx
  src/pages/Today.tsx
  src/types/arrangeBtnType.ts
Labels: 😻 승연, 🖼️ 뷰 퍼블리싱

#53 [FEAT TargetListArea 퍼블리싱
  src/components/common/button/ArrangeBtn.tsx
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetAreaDate.tsx
  src/components/targetArea/TargetControlSection.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/pages/Setting.tsx
  src/pages/Today.tsx
Labels: 😻 승연, 🖼️ 뷰 퍼블리싱

#57 [FEAT] Theme 최신화
  src/assets/svg/index.ts
  src/components/common/BtnDate/BtnDate.tsx
  src/components/common/BtnDate/BtnDateText.tsx
  src/components/common/BtnDate/BtnStagingDate.tsx
  src/components/common/NavBar.tsx
  src/components/common/NavBarIcon.tsx
  src/components/common/button/ArrangeBtn.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalTextInputTime.tsx
  src/components/common/textbox/TextInputDesc.tsx
  src/components/common/textbox/TextInputStaging.tsx
  src/components/common/textbox/TextInputTime.tsx
  src/components/common/textbox/TextInputTitle.tsx
  src/components/common/textbox/TextboxDailydate.tsx
  src/components/common/textbox/TextboxInput.tsx
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetControlSection.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/pages/Today.tsx
  src/styles/buttonTheme.ts
  src/styles/fontTheme.ts
  src/styles/palette.ts
  src/styles/theme.ts
Labels: 😻 승연

#60 [FEAT] 마감기한 공통컴포넌트 - 지연 상태일때의 스타일 추가
  src/components/common/BtnDate/BtnDate.tsx
  src/pages/Today.tsx
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱

#56 [FEAT] weekly 퍼블리싱
  package.json
  src/components/common/button/RefreshBtn.tsx
  src/components/common/fullCalendar/DayHeaderContent.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/fullCalendar/FullCalendarStyle.ts
  src/components/common/fullCalendar/fullCalendarUtils.ts
  src/pages/Calendar.tsx
  src/styles/GlobalStyle.tsx
  src/styles/palette.ts
  yarn.lock
Labels: 🏰 성희, 🖼️ 뷰 퍼블리싱

#61 [FEAT] Task 컴포넌트 퍼블리싱
  src/assets/svg/icn_file.svg
  src/assets/svg/icn_hover_indicator.svg
  src/assets/svg/index.ts
  src/components/common/BtnDate/BtnDate.tsx
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/button/Check1Btn.tsx
  src/components/common/button/settingBtn/SettingCheck4Btn.tsx
  src/components/common/button/settingBtn/SettingDeleteBtn.tsx
  src/components/common/button/statusBtn/StatusDoneBtn.tsx
  src/components/common/button/statusBtn/StatusInProgressBtn.tsx
  src/components/common/button/statusBtn/StatusStagingBtn.tsx
  src/components/common/button/statusBtn/StatusTodoBtn.tsx
  src/pages/Today.tsx
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱

#67 [FIX] Calandar, Clock, Line Icon stroke 색상 수정
  src/components/common/BtnDate/BtnDate.tsx
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱, 에러 수정

#69 [FEAT] 스크롤 하단(gradient 적용) 공통 컴포넌트 생성
  src/components/common/ScrollGradient.tsx
  src/pages/Today.tsx
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱

#71 [FIX] ScrollGradient 컴포넌트 위치 고정
  src/components/common/ScrollGradient.tsx
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱, 에러 수정

#63 [FEAT] setting 뷰 퍼블리싱
  src/assets/images/google_calendar.png
  src/assets/svg/index.ts
  src/assets/svg/line164.svg
  src/assets/svg/plus-circle.svg
  src/components/SettingPage/AccountArea.tsx
  src/components/SettingPage/LogOutBtn.tsx
  src/components/SettingPage/ProfileArea.tsx
  src/constants/users.ts
  src/pages/Setting.tsx
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱

#73 [FEAT] StagingArea 퍼블리싱
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaSetting.tsx
  src/components/common/button/EnterBtn.tsx
  src/components/common/button/textBtn/TextBtn.tsx
  src/components/common/button/textBtn/textBtnStyle.ts
  src/components/common/textbox/TextInputStaging.tsx
  src/pages/Today.tsx
  src/types/textBtnType.ts
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱

#79 [FEAT] 대시보드 뷰 task 요약 컴포넌트 퍼블리싱 (하단 컴포넌트)
  src/components/DashboardPage/TaskSummary.tsx
  src/constants/tasksPeriod.ts
  src/pages/DashBoard.tsx
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱

#75 [FIX] 공통 모달 퍼블리싱 수정
  src/assets/svg/SettingCheck1.svg
  src/assets/svg/SettingCheck1Icon.svg
  src/assets/svg/SettingCheck3Icon.svg
  src/assets/svg/SettingCheck4Icon.svg
  src/assets/svg/SettingXIcon.svg
  src/assets/svg/clock-check.svg
  src/assets/svg/index.ts
  src/components/SettingPage/AccountArea.tsx
  src/components/calendarPage/CategoryBox.tsx
  src/components/common/button/CancelWhiteBtn.tsx
  src/components/common/button/Check1Btn.tsx
  src/components/common/button/OkayCancelBtn.tsx
  src/components/common/button/settingBtn/SettingCheck2Btn.tsx
  src/components/common/button/settingBtn/SettingCheck3Btn.tsx
  src/components/common/button/settingBtn/SettingCheck4Btn.tsx
  src/components/common/button/settingBtn/SettingCheckBtn.tsx
  src/components/common/button/settingBtn/SettingXBtn.tsx
  src/components/common/button/settingBtn/settingBtnStyle.ts
  src/components/common/button/statusBtn/StatusDoneBtn.tsx
  src/components/common/button/statusBtn/StatusInProgressBtn.tsx
  src/components/common/button/statusBtn/StatusStagingBtn.tsx
  src/components/common/button/statusBtn/StatusTodoBtn.tsx
  src/components/common/button/textBtn/textBtnStyle.ts
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalHeaderBtn.tsx
  src/components/common/modal/ModalTextInputTime.tsx
  src/pages/Setting.tsx
Labels: 🏰 성희, 🖼️ 뷰 퍼블리싱

#76 [FEAT] Date Picker 제작
  .eslintrc.cjs
  package.json
  src/components/common/NavBarIcon.tsx
  src/components/common/arrangeBtn/ArrangeBtn.tsx
  src/components/common/datePicker/CustomHeader.tsx
  src/components/common/datePicker/DatePickerCustom.tsx
  src/components/common/datePicker/DatePickerStyle.tsx
  src/components/common/datePicker/DayDiffText.tsx
  src/components/common/textbox/TextboxInput.tsx
  src/main.tsx
  src/styles/buttonTheme.ts
  src/types/arrangeBtnType.ts
  src/utils/dotFormatDate.ts
  src/utils/formatDatetoString.ts
  src/utils/refStatus.ts
  yarn.lock
Labels: 😻 승연, 🖼️ 뷰 퍼블리싱, ⭐️ 기능 추가

#72 [FEAT] 대시보드 뷰 task 컴포넌트 퍼블리싱
  src/components/DashboardPage/DashboardTask.tsx
  src/constants/dashboardTask.ts
  src/constants/tasksToday.ts
  src/pages/DashBoard.tsx
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱

#89 [FIX] 공통 컴포넌트 text btn 크기 수정
  src/components/common/button/textBtn/TextBtn.tsx
  src/components/common/button/textBtn/textBtnStyle.ts
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱, 에러 수정

#84 [FIX] nav bar 우선 순위 및 배경색 조정
  src/components/common/NavBar.tsx
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱, 에러 수정

#82 [BUG] 공통 컴포넌트 버튼 색상 및 구조 변경
  src/assets/svg/Delete.svg
  src/components/common/button/DeleteBtn.tsx
  src/components/common/button/settingBtn/SettingDeleteBtn.tsx
  src/components/common/button/statusBtn/StatusStagingBtn.tsx
  src/components/common/modal/ModalHeaderBtn.tsx
  src/pages/Setting.tsx
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱, 에러 수정

#90 [FEAT] Arrange Modal 생성
  src/components/common/button/SortBtn.tsx
  src/components/common/modal/ModalArrange/ModalArrange.tsx
  src/constants/sortType.ts
  src/pages/Today.tsx
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱

#88 [FEAT] 카테고리 박스 퍼블리싱
  src/assets/svg/ic_selectbox_selected.svg
  src/assets/svg/ic_selectbox_unselected.svg
  src/assets/svg/index.ts
  src/components/calendarPage/CategoryBox.tsx
  src/components/calendarPage/CategoryCheckBox.tsx
  src/pages/Calendar.tsx
Labels: 🏰 성희, 🖼️ 뷰 퍼블리싱

#91 [FEAT] 날짜, 시간 수정 데이트피커 모달 제작
  src/components/common/datePicker/CorrectionCustomHeader.tsx
  src/components/common/datePicker/CustomHeader.tsx
  src/components/common/datePicker/DateCorrectionModal.tsx
  src/components/common/datePicker/DatePickerStyle.tsx
  src/components/common/textbox/TextboxInput.tsx
  src/pages/DashBoard.tsx
Labels: 😻 승연, 🖼️ 뷰 퍼블리싱

#93 [FEAT] 시간 포맷팅 추가
  src/components/common/datePicker/DateCorrectionModal.tsx
  src/components/common/textbox/TextboxInput.tsx
  src/utils/checkTimeFormat.ts
  src/utils/dotFormatTime.ts
Labels: 😻 승연, ⭐️ 기능 추가

#95 [FEAT] 미니캘린더 제작
  src/components/calendarPage/miniCalendar/MiniCalendar.tsx
  src/components/calendarPage/miniCalendar/MiniCalendarHeader.tsx
  src/components/calendarPage/miniCalendar/MiniCalendarStyle.tsx
  src/components/targetArea/TargetAreaDate.tsx
  src/pages/Calendar.tsx
  src/utils/getToday.ts
Labels: 😻 승연, 🖼️ 뷰 퍼블리싱, ⭐️ 기능 추가

#99 [FEAT] 날짜 인풋 유효성 검사
  src/components/common/textbox/TextboxInput.tsx
  src/utils/checkDateFormat.ts
Labels: 😻 승연, ⭐️ 기능 추가

#101 [FIX] styled-coponent에 props 전달 오류 수정
  src/components/common/BtnDate/BtnDate.tsx
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱, 에러 수정

#102 [FEAT] 모달 취소, 삭제 버튼 추가 구현
  src/components/common/button/settingBtn/SettingDeleteBtn.tsx
  src/components/common/modal/ModalDeleteBtn.tsx
  src/components/common/modal/ModalDeleteDetail.tsx
  src/components/common/modal/ModalHeaderBtn.tsx
Labels: 🏰 성희, 🖼️ 뷰 퍼블리싱

#109 [FIX] BtnType props 타입 및 height 수정
  src/components/common/BtnDate/BtnDate.tsx
  src/components/common/BtnTask/BtnTask.tsx
  src/pages/Today.tsx
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱, 에러 수정

#108 [FEAT] 캘린더 뷰 퍼블리싱
  src/components/calendarPage/CategoryBox.tsx
  src/components/common/fullCalendar/FullCalendarStyle.ts
  src/pages/Calendar.tsx
Labels: 🏰 성희, 🖼️ 뷰 퍼블리싱

#111 [FEAT] Today 페이지 퍼블리싱 + StagingArea 모달 연결
  src/components/common/BtnDate/BtnStagingDate.tsx
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaSetting.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/datePicker/DateCorrectionModal.tsx
  src/components/common/fullCalendar/FullCalendarStyle.ts
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalArrange/ModalArrange.tsx
  src/components/common/textbox/TextInputStaging.tsx
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/pages/MainLayout.tsx
  src/pages/Setting.tsx
  src/pages/Today.tsx
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱

#114 [FIX] Task 할당 모달 스타일 수정
  src/components/common/button/settingBtn/SettingDeleteBtn.tsx
  src/components/common/modal/ModalDeleteBtn.tsx
  src/components/common/modal/ModalDeleteDetail.tsx
  src/components/common/textbox/TextInputDesc.tsx
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱

#106 [FEAT] TextBoxInput 날짜, 시간 체크 실패시 피드백
  src/components/common/datePicker/CorrectionCustomHeader.tsx
  src/components/common/datePicker/CustomHeader.tsx
  src/components/common/datePicker/DateCorrectionModal.tsx
  src/components/common/datePicker/DatePickerCustom.tsx
  src/components/common/textbox/TextboxInput.tsx
  src/utils/formatDatetoString.ts
  src/utils/refStatus.ts
Labels: 😻 승연, ⭐️ 기능 추가

#116 [INIT] react query 세팅
  .eslintrc.cjs
  package.json
  src/main.tsx
  yarn.lock
Labels: 😻 승연, 🔧 초기세팅

#119 [FEAT] TaskBtn 더블클릭, 클릭 인터랙션 분리
  src/components/common/BtnDate/BtnDate.tsx
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/BtnTask/IconHoverContainer.tsx
  src/components/common/button/OkayCancelBtn.tsx
  src/components/common/modal/Modal.tsx
Labels: 😻 승연, ⭐️ 기능 추가

#124 [FEAT] 확인취소버튼 스토리북 등록
  .storybook/preview.ts
  .storybook/preview.tsx
  src/stories/Button/OkayCancelBtn.stories.ts
Labels: 😻 승연, 🔧 초기세팅

#122 [FEAT] fullCalendar task와 schedule 구분
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/fullCalendar/FullCalendarStyle.ts
  src/styles/GlobalStyle.tsx
Labels: 🏰 성희, 🖼️ 뷰 퍼블리싱

#121 [FEAT] Today 뷰 모달 연결
  src/components/common/BtnDate/BtnDate.tsx
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/StagingArea/StagingAreaSetting.tsx
  src/components/common/datePicker/DateCorrectionModal.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalBackdrop.tsx
  src/components/common/modal/ModalDeleteDetail.tsx
  src/components/common/textbox/TextInputDesc.tsx
  src/components/common/textbox/TextInputStaging.tsx
  src/components/targetArea/TargetControlSection.tsx
  src/constants/modalLocation.ts
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱

#127 [FEAT] 캘린더 날짜 맞추기
  src/components/calendarPage/miniCalendar/MiniCalendar.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/pages/Calendar.tsx
Labels: 🏰 성희, ⭐️ 기능 추가

#128 [FEAT] 스크롤할 때만 스크롤바 보이도록 설정
  src/components/common/BtnTaskContainer.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/targetArea/TargetTaskSection.tsx
Labels: 😻 승연, ⭐️ 기능 추가

#129 [FEAT] FullCalendar events에 모달 연결
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/constants/modalLocation.ts
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱

#134 [FEAT] 텍스트 드래그 방지
  src/styles/GlobalStyle.tsx
Labels: 🏰 성희, ⭐️ 기능 추가

#139 [FIX] GlobalStyle 버튼 커서 추가
  src/styles/GlobalStyle.tsx
Labels: 🫧 지민, 🔧 초기세팅

#135 [FEAT] 대시보드 뷰 구현
  src/components/DashboardPage/DashboardTask.tsx
  src/components/DashboardPage/DashboardTaskWrapper.tsx
  src/components/DashboardPage/DateArea.tsx
  src/components/DashboardPage/DatePickerPlaceholder.tsx
  src/components/DashboardPage/TaskSummary.tsx
  src/components/DashboardPage/pastDateBtnStyle.ts
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/button/statusBtn/StatusDoneBtn.tsx
  src/components/common/button/statusBtn/StatusTodoBtn.tsx
  src/components/common/button/textBtn/TextBtn.tsx
  src/components/common/button/textBtn/textBtnStyle.ts
  src/components/common/datePicker/DatePickerCustom.tsx
  src/components/common/datePicker/DatePickerStyle.tsx
  src/pages/DashBoard.tsx
  src/utils/getNameOfDayKor.ts
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱

#151 [FEAT] 잘못된 접근 페이지 퍼블리싱
  src/assets/images/index.ts
  src/assets/images/loginBg.png
  src/assets/images/notFoundBg.png
  src/assets/images/smallLogo.png
  src/pages/NotFound.tsx
Labels: 😻 승연, 🖼️ 뷰 퍼블리싱

#144 [FEAT] datepicker 값 버튼에 연결
  src/components/DashboardPage/DateArea.tsx
  src/components/DashboardPage/DatePickerPlaceholder.tsx
  src/components/common/datePicker/DatePickerCustom.tsx
  src/constants/getPastDate.ts
  src/pages/Calendar.tsx
  src/utils/formatDatetoStringKor.ts
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱, ⭐️ 기능 추가

#146 [FEAT] 구글 소셜 로그인 api 연결
  .gitignore
  package.json
  src/apis/instance.ts
  src/apis/login/loginAxios.ts
  src/apis/login/loginInterface.ts
  src/apis/messages.ts
  src/main.tsx
  src/pages/Login.tsx
  yarn.lock
Labels: 🏰 성희, ⭐️ 기능 추가

#147 [FEAT] 모달에 정보 연결하기
  src/components/common/BtnDate/BtnDate.tsx
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/BtnTaskContainer.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/datePicker/CorrectionCustomHeader.tsx
  src/components/common/datePicker/CustomHeader.tsx
  src/components/common/datePicker/DateCorrectionModal.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalDeleteDetail.tsx
  src/components/common/modal/TextInputBox.tsx
  src/components/common/textbox/TextInputDesc.tsx
  src/components/common/textbox/TextInputStaging.tsx
  src/components/common/textbox/TextInputTitle.tsx
  src/components/common/textbox/TextboxInput.tsx
  src/components/targetArea/TargetControlSection.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/stories/Button/OkayCancelBtn.stories.ts
  src/types/tasks/taskType.ts
Labels: 😻 승연, ⭐️ 기능 추가

#152 [FEAT] 로그인 뷰 퍼블리싱
  src/assets/images/googleIcon.png
  src/assets/images/index.ts
  src/assets/images/titleIcon.png
  src/pages/Login.tsx
  src/pages/Today.tsx
Labels: 🏰 성희, 🖼️ 뷰 퍼블리싱

#156 [FEAT] 세팅 페이지 취소, 삭제 버튼 추가
  src/components/SettingPage/AccountArea.tsx
  src/components/SettingPage/AccountDeleteBtn.tsx
  src/components/common/button/DeleteCancelBtn.tsx
  src/components/common/modal/ModalDeleteDetail.tsx
  src/pages/Setting.tsx
Labels: 🏰 성희, 🖼️ 뷰 퍼블리싱

#160 [FIX] Task버튼 스타일 및 hover Icon 수정사항 반영
  src/components/DashboardPage/DashboardTask.tsx
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/BtnTask/IconHoverContainer.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/targetArea/TargetTaskSection.tsx
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱

#162 [FEAT] 대시보드 뷰 테스크 버튼 더블클릭 시 모달 노출 막기
  .gitignore
  src/components/DashboardPage/DashboardTask.tsx
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/targetArea/TargetTaskSection.tsx
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱, ⭐️ 기능 추가

#164 [FEAT] yaml 파일 env 변수추가
  .github/workflows/gradle.yaml
Labels: 😻 승연, 배포

#143 [FEAT] Task 드래그앤드롭 기능 구현
  package.json
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/BtnTaskContainer.tsx
  src/components/common/ScrollGradient.tsx
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/textbox/TextInputStaging.tsx
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/main.tsx
  src/pages/Today.tsx
  yarn.lock
Labels: 🍀 지원, ⭐️ 기능 추가

#169 [FEAT] Task 리스트 조회 api 연결
  src/App.tsx
  src/Router.tsx
  src/apis/tasks/getTask/GetTasksType.ts
  src/apis/tasks/getTask/axios.ts
  src/apis/tasks/getTask/query.ts
  src/apis/timeBlocks/.gitkeep
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaSetting.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/modal/ModalArrange/ModalArrange.tsx
  src/components/loginPage/GoogleLoginBtn.tsx
  src/constants/sortType.ts
  src/main.tsx
  src/pages/Login.tsx
  src/router/PrivateRoute.tsx
  src/router/Router.tsx
  src/types/sortOrderType.ts
Labels: 😻 승연, 🔗 api 연결

#170 [FEAT] today 페이지의 날짜 이동 기능
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetAreaDate.tsx
  src/components/targetArea/TargetControlSection.tsx
Labels: 🏰 성희, ⭐️ 기능 추가

#176 [FEAT] 대시보드 empty 뷰 구현
  src/assets/svg/Empty_Postpone.svg
  src/assets/svg/Empty_Task.svg
  src/assets/svg/index.ts
  src/components/DashboardPage/DashboardTask.tsx
  src/constants/dashboardTask.ts
  src/constants/tasksPeriod.ts
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱, ⭐️ 기능 추가

#183 [REFACTOR] svg 파일 png로 변환
  src/assets/images/Empty_Postpone.png
  src/assets/images/Empty_Task.png
  src/assets/images/index.ts
  src/assets/svg/index.ts
  src/components/DashboardPage/DashboardTask.tsx
  src/components/DashboardPage/DashboardTaskWrapper.tsx
Labels: 🫧 지민, 에러 수정

#175 [FEAT] task get api TargetArea 연동
  src/apis/tasks/getTask/GetTasksType.ts
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/utils/formatDatetoLocalDate.ts
Labels: 😻 승연, 🔗 api 연결

#180 [FEAT] Task type별 리스트 조회 api 연결
  src/apis/dashboard/tasksToday/TasksTodayType.ts
  src/apis/dashboard/tasksToday/axios.ts
  src/apis/dashboard/tasksToday/query.ts
  src/apis/tasks/getTask/axios.ts
  src/components/DashboardPage/DashboardTask.tsx
  src/components/DashboardPage/DashboardTaskWrapper.tsx
Labels: 😻 승연, 🔗 api 연결

#181 [FEAT] 로그아웃 api 연결
  src/apis/instance.ts
  src/apis/logout/logoutAxios.ts
  src/components/SettingPage/LogOutBtn.tsx
Labels: 🏰 성희, 🔗 api 연결

#186 [FIX] 대시보드 뷰 하단 컴포넌트 이미지 삽입
  src/assets/images/Dashboard_Inprogress.png
  src/assets/images/Dashboard_Postpone.png
  src/assets/images/Dashboard_Progress.png
  src/assets/images/Dashboard_Upcoming.png
  src/assets/images/index.ts
  src/components/DashboardPage/TaskSummary.tsx
  src/pages/DashBoard.tsx
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱, 에러 수정

#189 [FEAT] today empty 뷰 퍼블리싱
  src/apis/tasks/getTask/query.ts
  src/components/common/EmptyContainer.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/targetArea/TargetTaskSection.tsx
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱, ⭐️ 기능 추가

#187 [FEAT] Task 기간별 조회 api 연결
  src/apis/dashboard/tasksPeriod/axios.ts
  src/apis/dashboard/tasksPeriod/query.ts
  src/apis/dashboard/tasksPeriod/taskPeriodType.ts
  src/components/DashboardPage/DashboardDateContainer.tsx
  src/components/DashboardPage/DateArea.tsx
  src/components/common/datePicker/DatePickerCustom.tsx
  src/constants/dashboardSummaryInfo.ts
  src/pages/DashBoard.tsx
Labels: 😻 승연, 🔗 api 연결

#192 [FEAT] Task 상태 수정 api (드래그앤드롭 부분 우선 구현)
  src/apis/tasks/getTask/GetTasksResponse.ts
  src/apis/tasks/getTask/query.ts
  src/apis/tasks/updateTaskStatus/UpdateTaskStatusType.ts
  src/apis/tasks/updateTaskStatus/axios.ts
  src/apis/tasks/updateTaskStatus/query.ts
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaSetting.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetAreaDate.tsx
  src/components/targetArea/TargetControlSection.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/pages/Today.tsx
  src/types/today/TargetControlSectionProps.ts
  src/types/today/stagingAreaSettingProps.ts
Labels: 🍀 지원, 🔗 api 연결

#196 [BUG] 태스크 클릭 후 이벤트 생성
  src/pages/Today.tsx
Labels: 😻 승연, 에러 수정

#200 [FEAT] 유저 정보 조회 api 연결
  src/apis/user/axios.ts
  src/apis/user/query.ts
  src/apis/user/userInfoType.ts
  src/components/SettingPage/AccountArea.tsx
  src/components/SettingPage/ProfileArea.tsx
  src/components/common/NavBar.tsx
  src/components/common/spinner/Spinner.tsx
  src/constants/users.ts
  src/pages/Setting.tsx
Labels: 🏰 성희, 🔗 api 연결

#198 [FEAT] Task 생성 api 연결
  src/apis/tasks/createTask/CreateTaskType.ts
  src/apis/tasks/createTask/axios.ts
  src/apis/tasks/createTask/query.ts
  src/components/common/button/EnterBtn.tsx
  src/components/common/datePicker/DateCorrectionModal.tsx
  src/components/common/textbox/TextInputStaging.tsx
Labels: 😻 승연, 🫧 지민, 🔗 api 연결

#205 [FIX] 대시보드 뷰 이미지 경로 수정
  src/constants/dashboardSummaryInfo.ts
Labels: 🫧 지민, 에러 수정

#206 [FEAT] Task 삭제 api 연결
  src/apis/tasks/deleteTask/axios.ts
  src/apis/tasks/deleteTask/query.ts
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/BtnTask/IconHoverContainer.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/button/statusBtn/StatusStagingBtn.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/pages/Today.tsx
Labels: 😻 승연, 🫧 지민, 🔗 api 연결

#207 [FEAT] Today 페이지 정리
  src/pages/Today.tsx
Labels: 😻 승연

#210 [FEAT] 화면 백그라운드 설정
  src/App.tsx
  src/components/common/BackGroundLayout.tsx
  src/components/common/NavBar.tsx
  src/pages/Login.tsx
  src/pages/MainLayout.tsx
  src/pages/NotFound.tsx
Labels: 😻 승연, 🖼️ 뷰 퍼블리싱

#209 [FEAT] 구글 캘린더 연동 해제 api 구현
  src/apis/calendar/addCalendar/axios.ts
  src/apis/calendar/addCalendar/query.ts
  src/apis/calendar/deleteCalendar/axios.ts
  src/apis/calendar/deleteCalendar/query.ts
  src/apis/calendarAccount/axios.ts
  src/components/SettingPage/AccountArea.tsx
  src/components/SettingPage/AccountDeleteBtn.tsx
  src/components/SettingPage/GoogleCalendarBtn.tsx
  src/components/common/modal/ModalDeleteDetail.tsx
Labels: 🏰 성희, 🔗 api 연결

#211 [FEAT] Time-block 리스트 조회
  src/apis/timeBlocks/deleteTimeBlock/axios.ts
  src/apis/timeBlocks/getTimeBlock/GetTimeBlock.ts
  src/apis/timeBlocks/getTimeBlock/GetTimeBlockType.ts
  src/apis/timeBlocks/getTimeBlock/axios.ts
  src/apis/timeBlocks/getTimeBlock/query.ts
  src/apis/timeBlocks/postTimeBlock/PostTimeBlockType.ts
  src/apis/timeBlocks/postTimeBlock/axios.ts
  src/apis/timeBlocks/postTimeBlock/query.ts
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/fullCalendar/processEvents.tsx
  src/utils/getStartDayOfMonth.ts
  src/utils/getStartDayOfWeek.ts
Labels: 🍀 지원, 🔗 api 연결

#216 [FEAT] 구글 캘린더 카테고리 리스트 조회 api 구현
  src/apis/categoryList/axios.ts
  src/apis/categoryList/categoryResponse.ts
  src/apis/categoryList/query.ts
  src/assets/images/Empty_Category.png
  src/assets/images/index.ts
  src/components/calendarPage/CategoryBox.tsx
  src/pages/Calendar.tsx
Labels: 🏰 성희, 🔗 api 연결

#217 [FEAT] Task 타임블로킹 생성 api 연결
  src/apis/timeBlocks/postTimeBlock/PostTimeBlockType.ts
  src/apis/timeBlocks/postTimeBlock/axios.ts
  src/apis/timeBlocks/postTimeBlock/query.ts
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/pages/Today.tsx
Labels: 🍀 지원, 🔗 api 연결

#219 [FEAT] 풀캘린더 영역 넘어가는 이벤트 글자 처리
  src/components/common/fullCalendar/FullCalendarStyle.ts
Labels: 🏰 성희, 🖼️ 뷰 퍼블리싱

#220 [FEAT] Task 타임블로킹 삭제 api 연결
  src/apis/timeBlocks/deleteTimeBlock/DeleteTimeBlockType.ts
  src/apis/timeBlocks/deleteTimeBlock/axios.ts
  src/apis/timeBlocks/deleteTimeBlock/query.ts
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/fullCalendar/processEvents.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalDeleteBtn.tsx
  src/components/common/modal/ModalDeleteDetail.tsx
  src/components/common/modal/ModalHeaderBtn.tsx
Labels: 🍀 지원, 🔗 api 연결

#223 [BUG] 승연이의 짬뽕탕 (태스크 생성 기한 설정 모달 값 입력 이슈 & UI 수정사항 & 불필요한 값 삭제)
  src/components/DashboardPage/DashboardTask.tsx
  src/components/common/BtnDate/BtnDate.tsx
  src/components/common/BtnDate/BtnStagingDate.tsx
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/BtnTask/IconHoverContainer.tsx
  src/components/common/ScrollGradient.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/textbox/TextInputStaging.tsx
  src/pages/DashBoard.tsx
  src/pages/Today.tsx
Labels: 😻 승연, 에러 수정

#221 [FEAT] Task 타임블로킹 수정 api 연결
  src/apis/timeBlocks/deleteTimeBlock/DeleteTimeBlockType.ts
  src/apis/timeBlocks/deleteTimeBlock/axios.ts
  src/apis/timeBlocks/deleteTimeBlock/query.ts
  src/apis/timeBlocks/updateTimeBlock/PatchTimeBlockType.ts
  src/apis/timeBlocks/updateTimeBlock/axios.ts
  src/apis/timeBlocks/updateTimeBlock/query.ts
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/fullCalendar/processEvents.tsx
Labels: 🍀 지원, 🔗 api 연결

#227 [FEAT] BtnTask 호버 완료버튼 뮤테이션 연결
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/BtnTask/IconHoverContainer.tsx
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/button/statusBtn/StatusStagingBtn.tsx
  src/pages/Today.tsx
Labels: 😻 승연, ⭐️ 기능 추가

#231 [HOTFIX] develop 충돌 해결 과정에서의 timeBlockId 삭제 에러 해결
  src/components/common/fullCalendar/FullCalendarBox.tsx
Labels: 🍀 지원, 에러 수정, 🔗 api 연결

#230 [FEAT] 구글 캘린더 동기화 버튼 api 구현
  src/apis/timeBlocks/googleTimeBlock/axios.ts
  src/apis/timeBlocks/googleTimeBlock/query.ts
  src/components/common/button/RefreshBtn.tsx
  src/components/common/spinner/Spinner.tsx
Labels: 🏰 성희, 🔗 api 연결

#232 [FIX] 캘린더 스크롤바 스타일 수정 & 이용약관 링크 수정
  src/components/calendarPage/CategoryBox.tsx
  src/components/common/fullCalendar/FullCalendarStyle.ts
  src/pages/Login.tsx
Labels: 🏰 성희, ⭐️ 기능 추가

#236 [FIX] 모달안에 datepicker 가려짐 수정
  src/components/common/BtnDate/BtnDate.tsx
  src/components/common/datePicker/DatePickerStyle.tsx
Labels: 🏰 성희, 에러 수정

#238 [FEAT] 일정 추가에서 로직 보완
  src/components/common/textbox/TextInputStaging.tsx
Labels: 🏰 성희, ⭐️ 기능 추가

#242 [FEAT] Task 모달을 통한 삭제 api 연결
  src/components/common/modal/Modal.tsx
Labels: 🍀 지원, 🔗 api 연결

#244 [FIX] 버튼 대공사
  src/apis/tasks/updateTaskStatus/query.ts
  src/assets/svg/SettingCheck4Icon.svg
  src/components/DashboardPage/DashboardTask.tsx
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/BtnTask/BtnTaskIconRender.tsx
  src/components/common/BtnTask/DashboardIconHoverContainer.tsx
  src/components/common/BtnTask/IconHoverContainer.tsx
  src/components/common/BtnTask/StagingIconHoverContainer.tsx
  src/components/common/BtnTask/TargetIconHoverContainer.tsx
  src/components/common/BtnTask/useIconHoverUtil.ts
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/button/TodayPlusBtn.tsx
  src/components/common/button/settingBtn/SettingCheckBtn.tsx
  src/components/common/button/statusBtn/StatusDoneBtn.tsx
  src/components/common/button/statusBtn/StatusInProgressBtn.tsx
  src/components/common/button/statusBtn/StatusStagingBtn.tsx
  src/components/common/button/statusBtn/StatusTodoBtn.tsx
  src/components/common/modal/ModalHeaderBtn.tsx
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/types/today/BtnTaskLocationType.ts
Labels: 😻 승연, 🖼️ 뷰 퍼블리싱, ⭐️ 기능 추가, 에러 수정, 🔗 api 연결

#247 [FEAT] Task 설명 수정 api 연결
  src/apis/tasks/editTask/EditTaskDescriptionType.ts
  src/apis/tasks/editTask/axios.ts
  src/apis/tasks/editTask/query.ts
  src/components/common/BtnDate/BtnDate.tsx
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/TextInputBox.tsx
  src/components/common/textbox/TextInputDesc.tsx
  src/components/common/textbox/TextInputStaging.tsx
  src/components/common/textbox/TextInputTitle.tsx
  src/components/targetArea/TargetTaskSection.tsx
Labels: 🍀 지원, 🔗 api 연결

#249 [REFACTOR] 마감기한설정 컴포넌트 UI 개선
  src/components/common/textbox/TextInputStaging.tsx
  src/types/textInputType.ts
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱

#246 [FIX] placeholer 값 반영 수정
  src/components/DashboardPage/DateArea.tsx
  src/components/common/datePicker/DatePickerCustom.tsx
Labels: 🫧 지민, 에러 수정

#250 [FEAT] 풀캘린더 일정 선택 관련 기능 추가
  src/apis/timeBlocks/postTimeBlock/axios.ts
  src/apis/timeBlocks/postTimeBlock/query.ts
  src/apis/timeBlocks/postTimeBlock/timeblockType.ts
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/components/toast/Toast.tsx
  src/components/toast/ToastContainer.tsx
  src/components/toast/ToastContext.tsx
  src/main.tsx
  src/pages/Today.tsx
  src/styles/GlobalStyle.tsx
Labels: 🏰 성희, ⭐️ 기능 추가

#252 [HOTFIX] 리드미 개큰 업데이트
  README.md
Labels: 🏰 성희, 😻 승연, 🫧 지민, 🍀 지원

#260 [HOTFIX] StagingArea에서 Task 모달 띄울 시 에러 수정
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/pages/Today.tsx
Labels: 🍀 지원, 에러 수정, 🔗 api 연결

#261 [HOTFIX] 할 일 앤터로 입력 시 마지막 글자가 한 번 더 입력되는 버그 수정
  src/components/common/textbox/TextInputStaging.tsx
Labels: 🏰 성희, 에러 수정

#262 [HOTFIX] 달력 모달 위치 조정
  src/components/common/BtnDate/BtnDate.tsx
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱, 에러 수정

#266 [HOTFIX] 상태 변경 호버 지속상태 수정
  src/apis/dashboard/tasksToday/query.ts
  src/apis/tasks/updateTaskStatus/query.ts
  src/components/common/BtnTask/TargetIconHoverContainer.tsx
  src/components/common/button/TodayPlusBtn.tsx
  src/components/common/button/settingBtn/SettingCheckBtn.tsx
  src/components/common/button/statusBtn/StatusDoneBtn.tsx
  src/components/common/button/statusBtn/StatusInProgressBtn.tsx
  src/components/common/button/statusBtn/StatusTodoBtn.tsx
  src/pages/Today.tsx
Labels: 😻 승연, 에러 수정

#272 [FIX] 날짜 타입 변경
  src/components/common/BtnDate/BtnDate.tsx
  src/components/common/modal/Modal.tsx
  src/utils/parseDate.ts
Labels: 🫧 지민, 에러 수정

#270 [FEAT] 구글캘린더 타임블록 정보 수정(위치이동) 막기
  src/components/common/fullCalendar/FullCalendarBox.tsx
Labels: 🍀 지원, ⭐️ 기능 추가

#269 [FIX] 주말 색상 변경
  src/components/common/fullCalendar/FullCalendarStyle.ts
Labels: 🏰 성희, 🖼️ 뷰 퍼블리싱

#273 [FEAT] 타임블록 안에서 일정 옮길 때도 토스트 알림
  src/apis/timeBlocks/updateTimeBlock/axios.ts
  src/apis/timeBlocks/updateTimeBlock/query.ts
  src/pages/Today.tsx
  src/types/area/areaType.ts
Labels: 🏰 성희, ⭐️ 기능 추가

#276 [FIX] 대시보드 뷰 지난 날짜 버튼 클릭시 모달에 반영
  src/components/common/datePicker/DatePickerCustom.tsx
Labels: 🫧 지민, ⭐️ 기능 추가, 에러 수정
