Repository TEAM-DAWM/SHELLIN-CLIENT, pull requests merged in 2025-04, with the labels that each got.

#422 [FIX] 타임블록 관련 QA 수정
  src/apis/timeBlocks/postTimeBlock/query.ts
  src/apis/timeBlocks/updateTimeBlock/query.ts
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/fullCalendar/FullCalendarStyle.ts
  src/components/common/modal/Modal.tsx
  src/components/common/v2/dropdown/CalendarSettingDropdown.tsx
  src/components/common/v2/modal/MainSettingModal.tsx
  src/components/toast/Toast.tsx
  src/stories/Common/dropdown/CalendarSettingDropdown.stories.ts
  src/utils/formatDateTime.ts
Labels: 🏰 성희, 에러 수정, v2

#423 [ FIX] 토스트 undo 기능 있는 경우만 표시
  src/apis/tasks/updateTaskStatus/query.ts
  src/components/toast/Toast.tsx
  src/components/toast/ToastContainer.tsx
  src/components/toast/ToastContext.tsx
Labels: 😻 승연, v2

#431 [FIX] update GIT_USER config
  .github/workflows/test-link-deploy.yml
Labels: 에러 수정, 배포

#427 [REFACTOR] 모달 포지셔닝 & 오픈로직 변경
  src/components/common/datePicker/DateCorrectionModal.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/modal/ModalBackdrop.tsx
  src/components/common/v2/modal/MainSettingModal.tsx
  src/components/common/v2/popup/DateBtn.tsx
Labels: 🍀 지원, v2, 💪 기능 개선

#434 [FIX] fix test deploy error
  .github/workflows/test-link-deploy.yml
Labels: 🍀 지원, 에러 수정, 배포

#429 [FIX] 캘린더 today 영역 오늘 버튼 연동 끊기
  src/pages/Today.tsx
Labels: 😻 승연, 에러 수정

#436 [FIX] 캘린더 모달 오늘 버튼 동작 정상화
  src/components/common/datePicker/CorrectionCustomHeader.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
Labels: 🍀 지원, 에러 수정, v2

#437 [FIX] 기존 toast의 타입 conflict에서 info로 수정
  src/apis/timeBlocks/postTimeBlock/query.ts
  src/apis/timeBlocks/updateTimeBlock/query.ts
  src/components/common/v2/modal/MainSettingModal.tsx
  src/components/toast/Toast.tsx
  src/types/toastType.ts
Labels: 🏰 성희, v2

#439 [REFACTOR] task click logic update
  .github/workflows/test-link-deploy.yml
  package.json
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/v2/taskBox/Todo.tsx
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/pages/Today.tsx
  src/store/useTaskSelectionStore.tsx
  src/stories/Common/Button/Todo.stories.tsx
  src/types/area/taskAreaType.ts
  yarn.lock
Labels: 🍀 지원, v2, 💪 기능 개선
