Repository TEAM-DAWM/SHELLIN-CLIENT, pull requests merged in 2025-01, with the labels that each got.

#319 [FEAT] datepicker 모달 디자인 수정
  src/components/common/BtnDate/BtnDate.tsx
  src/components/common/datePicker/CorrectionCustomHeader.tsx
  src/components/common/datePicker/DateCorrectionModal.tsx
  src/components/common/datePicker/DatePickerStyle.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/textbox/TextInputStaging.tsx
  src/components/common/v2/IconButton.tsx
  src/components/targetArea/TargetControlSection.tsx
  src/stories/Common/DateCorrectionModal.stories.tsx
Labels: 😻 승연, v2

#321 [FEAT] DumpingArea 제작
  src/components/DashboardPage/DashboardTask.tsx
  src/components/common/BtnTask/BtnTask.tsx
  src/components/common/BtnTaskContainer.tsx
  src/components/common/NavBar.tsx
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/modal/ModalArrange/ModalArrange.tsx
  src/components/common/v2/taskBox/Todo.tsx
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/pages/MainLayout.tsx
  src/pages/Today.tsx
  src/types/tasks/taskType.ts
Labels: 😻 승연, v2

#329 [FEAT] 아이콘버튼 점 추가
  src/components/common/v2/IconButton.tsx
  src/components/common/v2/button/Button.tsx
  src/stories/Common/Button/IconButton.stories.tsx
Labels: 😻 승연, v2

#331 [CHORE] maze 스크립트 제거
  index.html
Labels: 😻 승연

#328 [FEAT] 캘린더 v2 변경
  src/components/common/Icon.tsx
  src/components/common/fullCalendar/CalendarHeader.tsx
  src/components/common/fullCalendar/CustomDayCellContent.tsx
  src/components/common/fullCalendar/DayHeaderContent.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/fullCalendar/FullCalendarStyle.ts
  src/components/common/fullCalendar/fullCalendarUtils.ts
  src/components/common/v2/IconButton.tsx
  src/components/common/v2/TextBox/MainDate.tsx
  src/components/common/v2/popup/ClassificationBox.tsx
  src/components/common/v2/popup/DeadlineBox.tsx
  src/components/targetArea/TargetControlSection.tsx
  src/pages/Today.tsx
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱, v2

#334 [FEAT] 메인 세팅 모달 퍼블리싱
  src/components/common/v2/TextBox/PopUp.tsx
  src/components/common/v2/dropdown/TimeDropdown.tsx
  src/components/common/v2/modal/MainSettingModal.tsx
  src/components/common/v2/popup/DateBtn.tsx
  src/components/common/v2/popup/DateTimeBtn.tsx
  src/components/common/v2/popup/DeadlineBox.tsx
  src/components/common/v2/popup/TimeBtn.tsx
  src/stories/Common/dropdown/TimeDropdown.stories.ts
  src/stories/modal/MainSettingModal.stories.ts
Labels: 🏰 성희, 🖼️ 뷰 퍼블리싱, v2

#338 [FEAT] Dumping Area Task 생성 기능 연결
  src/apis/tasks/getTask/GetTasksType.ts
  src/apis/tasks/getTask/axios.ts
  src/apis/tasks/getTask/query.ts
  src/apis/tasks/orderTask/OrderTaskType.ts
  src/apis/tasks/orderTask/axios.ts
  src/apis/tasks/orderTask/query.ts
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaSetting.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/modal/ModalArrange/ModalArrange.tsx
  src/components/common/v2/TextBox/DumpingAreaBtn.tsx
  src/components/common/v2/dropdown/SortingDropdown.tsx
  src/components/common/v2/taskBox/Todo.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/constants/sortType.ts
  src/pages/Today.tsx
  src/stories/Common/dropdown/SortingDropdown.stories.ts
  src/types/sortOrderType.ts
  src/types/today/stagingAreaSettingProps.ts
Labels: 😻 승연, 🔗 api 연결, v2

#343 [BUG] custom order post api 연결 문제
  src/apis/tasks/orderTask/axios.ts
  src/pages/Today.tsx
Labels: 😻 승연, 에러 수정, v2

#346 [FEAT] DueDate모달 2차 연결
  src/components/common/BtnTaskContainer.tsx
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/v2/TextBox/DumpingAreaBtn.tsx
  src/components/common/v2/modal/DueDateModal.tsx
  src/components/common/v2/popup/DateTimeBtn.tsx
  src/components/common/v2/popup/DeadlineBox.tsx
  src/pages/Today.tsx
Labels: 😻 승연, 🔗 api 연결, v2

#344 [FEAT] DueDate모달 연결
  src/components/common/BtnTaskContainer.tsx
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/v2/TextBox/DumpingAreaBtn.tsx
  src/components/common/v2/modal/DueDateModal.tsx
  src/components/common/v2/popup/DateTimeBtn.tsx
  src/components/common/v2/popup/DeadlineBox.tsx
  src/pages/Today.tsx
  src/utils/time.ts
Labels: 😻 승연, 🔗 api 연결, v2

#351 [FEAT] timeblock 생성 기능+api 연결
  src/apis/timeBlocks/getTimeBlock/GetTimeBlockType.ts
  src/apis/timeBlocks/getTimeBlock/axios.ts
  src/apis/timeBlocks/getTimeBlock/query.ts
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/datePicker/DateCorrectionModal.tsx
  src/components/common/fullCalendar/CalendarHeader.tsx
  src/components/common/fullCalendar/CustomDayCellContent.tsx
  src/components/common/fullCalendar/DayHeaderContent.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/fullCalendar/FullCalendarStyle.ts
  src/components/common/fullCalendar/processEvents.tsx
  src/components/common/v2/TextBox/SubDate.tsx
  src/components/common/v2/dropdown/CalendarSettingDropdown.tsx
  src/components/common/v2/taskBox/Todo.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/hooks/useTodoEventHandler.ts
  src/pages/Calendar.tsx
  src/pages/Today.tsx
  src/stories/Common/Button/Todo.stories.tsx
Labels: 🍀 지원, ⭐️ 기능 추가, 🔗 api 연결, v2

#349 [FEAT] task 삭제, 상태 수정 api 연결
  src/apis/tasks/deleteTask/query.ts
  src/apis/tasks/updateTaskStatus/query.ts
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/v2/control/DropdownButton.tsx
  src/components/common/v2/modal/MainSettingModal.tsx
  src/components/common/v2/taskBox/Todo.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/constants/statuses.ts
  src/stories/Common/Button/DropdownButton.stories.ts
  src/stories/Common/Button/Todo.stories.tsx
  src/stories/Common/dropdown/StatusDropdown.stories.ts
  src/stories/modal/MainSettingModal.stories.ts
  src/types/tasks/taskType.ts
Labels: 🏰 성희, 🔗 api 연결, v2

#356 [FEAT] 조회 필터링 기능 추가
  src/apis/timeBlocks/getTimeBlock/GetTimeBlock.ts
  src/components/common/fullCalendar/CalendarHeader.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/fullCalendar/FullCalendarStyle.ts
  src/components/common/fullCalendar/processEvents.tsx
  src/components/common/v2/dropdown/CalendarSettingDropdown.tsx
  src/stories/Common/dropdown/CalendarSettingDropdown.stories.ts
Labels: 🍀 지원, ⭐️ 기능 추가, v2

#360 [FEAT] 캘린더 내부 미니캘린더 기능 연결
  src/components/common/datePicker/DateCorrectionModal.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/hooks/useOutsideClick.ts
Labels: 🍀 지원, ⭐️ 기능 추가, v2

#357 [FEAT] timeBlock 삭제 모달 생성 및 기능 구현
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/v2/button/Button.tsx
  src/components/common/v2/control/DropdownButton.tsx
  src/components/common/v2/modal/TimeBlockDeleteModal.tsx
  src/constants/modalLocation.ts
  src/constants/statuses.ts
  src/stories/Common/Button/DropdownButton.stories.ts
  src/stories/Common/Button/Todo.stories.tsx
  src/stories/Common/dropdown/StatusDropdown.stories.ts
  src/stories/modal/MainSettingModal.stories.ts
  src/types/tasks/taskType.ts
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱, ⭐️ 기능 추가, v2

#361 [FEAT] Task 상세 조회, 수정 기능 연결
  src/apis/tasks/editTask/query.ts
  src/apis/tasks/taskDescription/axios.ts
  src/apis/tasks/taskDescription/query.ts
  src/apis/tasks/updateTaskStatus/query.ts
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/v2/TextBox/PopUp.tsx
  src/components/common/v2/control/DropdownButton.tsx
  src/components/common/v2/modal/MainSettingModal.tsx
  src/components/common/v2/taskBox/Todo.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/hooks/useInput.ts
  src/pages/Today.tsx
  src/stories/modal/MainSettingModal.stories.ts
  src/types/tasks/taskType.ts
Labels: 😻 승연, ⭐️ 기능 추가, 🔗 api 연결, v2

#363 [FEAT] 캘린더 드롭 이벤트 생성 + 모달 타임블록 데이터 반영
  src/apis/timeBlocks/postTimeBlock/query.ts
  src/apis/timeBlocks/updateTimeBlock/query.ts
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/fullCalendar/FullCalendarStyle.ts
  src/components/common/v2/modal/MainSettingModal.tsx
  src/components/toast/Toast.tsx
  src/constants/modalLocation.ts
  src/stories/Common/toast/Toast.stories.tsx
  src/types/toastType.ts
Labels: 🍀 지원, ⭐️ 기능 추가, v2

#377 [FIX] #372 변경사항 중 일부 적용
  index.html
  src/components/common/v2/taskBox/Todo.tsx
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetTaskSection.tsx
Labels: 😻 승연, 에러 수정, v2

#375 [REFACTOR] 드래그 모션 개선 + Todo 상태변경 오류 수정
  index.html
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/v2/taskBox/Todo.tsx
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetTaskSection.tsx
Labels: 🍀 지원, 에러 수정, v2

#380 [FEAT] 앰티뷰 수정
  src/assets/images/EmptyStaging.png
  src/assets/images/EmptyToday.png
  src/assets/images/index.ts
  src/components/common/EmptyContainer.tsx
  src/components/common/EmptyViewStaging.tsx
  src/components/common/EmptyViewToday.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/targetArea/TargetTaskSection.tsx
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱, v2

#383 [FEAT] Navbar icon 추가
  src/components/common/Icon.tsx
  src/components/common/NavBar.tsx
  src/components/common/v2/button/NavbarButton.tsx
Labels: 🫧 지민, ⭐️ 기능 추가, v2

#385 [FIX] 모달위치 수정, staging 모달 인풋 동작하도록 수정
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/v2/taskBox/Todo.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/stories/Common/Button/Todo.stories.tsx
Labels: 😻 승연, 에러 수정

#388 [ FIX] Todo 컴포넌트 날짜, 시간 형식 맞추기
  src/components/DashboardPage/DashboardTask.tsx
  src/components/DashboardPage/DatePickerPlaceholder.tsx
  src/components/common/BtnDate/BtnDate.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/datePicker/CustomHeader.tsx
  src/components/common/datePicker/DateCorrectionModal.tsx
  src/components/common/datePicker/DatePickerCustom.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/textbox/TextInputStaging.tsx
  src/components/common/textbox/TextboxInput.tsx
  src/components/common/v2/TextBox/DumpingAreaBtn.tsx
  src/components/common/v2/modal/MainSettingModal.tsx
  src/components/common/v2/popup/DateBtn.tsx
  src/components/common/v2/taskBox/Todo.tsx
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetControlSection.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/pages/DashBoard.tsx
  src/pages/Today.tsx
  src/utils/dotFormatDate.ts
  src/utils/dotFormatTime.ts
  src/utils/formatDateTime.ts
  src/utils/formatDateWithDay.ts
  src/utils/formatDatetoLocalDate.ts
  src/utils/formatDatetoString.ts
  src/utils/formatDatetoStringKor.ts
  src/utils/parseDate.ts
Labels: 😻 승연, ⭐️ 기능 추가, 에러 수정

#387 [FIX] 폰트(프리텐다드) 404
  src/styles/font.css
  src/styles/font.ts
Labels: 😻 승연, 에러 수정

#386 [FIX] 로그인 페이지 반응형 수정
  src/pages/Login.tsx
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱, v2

#391 [ FIX] staging area order 모달 위치
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/v2/dropdown/SortingDropdown.tsx
Labels: 😻 승연, 에러 수정

#393 [FEAT] TimeBlock 종일이벤트 추가
  src/apis/timeBlocks/getTimeBlock/GetTimeBlock.ts
  src/apis/timeBlocks/postTimeBlock/PostTimeBlockType.ts
  src/apis/timeBlocks/postTimeBlock/axios.ts
  src/apis/timeBlocks/postTimeBlock/query.ts
  src/apis/timeBlocks/updateTimeBlock/PatchTimeBlockType.ts
  src/apis/timeBlocks/updateTimeBlock/axios.ts
  src/apis/timeBlocks/updateTimeBlock/query.ts
  src/components/common/datePicker/DateCorrectionModal.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/fullCalendar/FullCalendarStyle.ts
  src/components/common/fullCalendar/processEvents.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/v2/modal/MainSettingModal.tsx
  src/components/common/v2/modal/TimeBlockDeleteModal.tsx
  src/components/common/v2/popup/DateTimeBtn.tsx
  src/components/common/v2/popup/DeadlineBox.tsx
  src/types/tasks/taskType.ts
  src/utils/formatDateTime.ts
Labels: 🍀 지원, ⭐️ 기능 추가, 🔗 api 연결, v2

#395 [FIX] 앰티뷰 위치 수정
  src/components/common/EmptyViewStaging.tsx
  src/components/common/EmptyViewToday.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/targetArea/TargetTaskSection.tsx
Labels: 🫧 지민, 🖼️ 뷰 퍼블리싱, v2

#392 [ FIX] task delete 시 캘린더쪽 타임블럭쪽 쿼리키 Invalidate
  src/apis/tasks/deleteTask/query.ts
Labels: 😻 승연, 에러 수정

#399 [STYLE] 로그인 뷰 모바일 기기대응
  src/components/loginPage/GoogleLoginBtn.tsx
  src/pages/Login.tsx
Labels: 🍀 지원, 🖼️ 뷰 퍼블리싱, v2
