Repository TEAM-DAWM/SHELLIN-CLIENT, pull requests merged in 2025-03, with the labels that each got.

#404 [FIX] task drag&drop 깜박임 해결 및 task 수정 로직 점검
  src/apis/queryKeys.ts
  src/apis/tasks/createTask/query.ts
  src/apis/tasks/deleteTask/query.ts
  src/apis/tasks/editTask/EditTaskDescriptionType.ts
  src/apis/tasks/editTask/axios.ts
  src/apis/tasks/editTask/query.ts
  src/apis/tasks/getTask/query.ts
  src/apis/tasks/orderTask/query.ts
  src/apis/tasks/taskDescription/query.ts
  src/apis/tasks/updateTaskStatus/query.ts
  src/components/common/BtnTask/TargetIconHoverContainer.tsx
  src/components/common/NavBar.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/button/settingBtn/SettingCheckBtn.tsx
  src/components/common/datePicker/DateCorrectionModal.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/fullCalendar/FullCalendarStyle.ts
  src/components/common/v2/TextBox/DumpingAreaBtn.tsx
  src/components/common/v2/modal/DueDateModal.tsx
  src/components/common/v2/modal/MainSettingModal.tsx
  src/components/common/v2/popup/DateBtn.tsx
  src/components/common/v2/popup/DateTimeBtn.tsx
  src/components/common/v2/popup/DeadlineBox.tsx
  src/components/common/v2/taskBox/Todo.tsx
  src/main.tsx
  src/pages/Today.tsx
Labels: 🏰 성희, 에러 수정, v2

#408 [FIX] timeblock 및 calendar 반영 지연문제 해결 + UX개선
  src/apis/tasks/updateTaskStatus/query.ts
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/fullCalendar/FullCalendarStyle.ts
  src/components/common/fullCalendar/processEvents.tsx
Labels: 🍀 지원, 에러 수정, v2

#409 [FEAT] today영역 필터기능 추가
  src/apis/tasks/getTask/query.ts
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaSetting.tsx
  src/components/common/v2/dropdown/SortingDropdown.tsx
  src/components/targetArea/FilterSection.tsx
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetControlSection.tsx
  src/components/targetArea/TargetFilterSection.tsx
  src/pages/Today.tsx
  src/stories/Common/dropdown/SortingDropdown.stories.ts
  src/types/area/taskAreaType.ts
  src/types/today/TargetControlSectionProps.ts
  src/types/today/stagingAreaSettingProps.ts
Labels: 🏰 성희, ⭐️ 기능 추가, v2

#405 [FEAT] Toast 되돌리기
  src/apis/tasks/updateTaskStatus/query.ts
  src/components/toast/Toast.tsx
  src/components/toast/ToastContainer.tsx
  src/components/toast/ToastContext.tsx
Labels: 😻 승연, ⭐️ 기능 추가

#412 [REFACTOR] 쏟아내기 및 마감기한 UX 개선
  src/components/common/v2/TextBox/DumpingAreaBtn.tsx
  src/components/common/v2/button/Button.tsx
  src/components/common/v2/modal/DueDateModal.tsx
  src/components/common/v2/modal/MainSettingModal.tsx
  src/components/common/v2/popup/DateTimeBtn.tsx
  src/hooks/useInputHandler.ts
  src/utils/generateQuarterTimes.ts
  src/utils/time.ts
Labels: 🍀 지원, v2, 💪 기능 개선

#413 [FIX] main setting modal 상태 관리
  src/apis/tasks/editTask/query.ts
  src/apis/timeBlocks/updateTimeBlock/query.ts
  src/components/common/BtnTaskContainer.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/fullCalendar/FullCalendarStyle.ts
  src/components/common/v2/TextBox/PopUp.tsx
  src/components/common/v2/dropdown/TimeDropdown.tsx
  src/components/common/v2/modal/MainSettingModal.tsx
  src/components/common/v2/popup/DeadlineBox.tsx
  src/components/common/v2/popup/TimeBtn.tsx
  src/components/common/v2/taskBox/Todo.tsx
  src/hooks/useInput.ts
  src/hooks/useInputHandler.ts
  src/stories/Common/dropdown/TimeDropdown.stories.ts
  src/stories/modal/MainSettingModal.stories.ts
  src/utils/formatTime.ts
  src/utils/formatTimeWithAmPm.ts
  src/utils/generateQuarterTimes.ts
  src/utils/time.ts
Labels: 🏰 성희, 에러 수정, v2

#415 [CHORE] develop 브랜치 내역 자동 배포 CICD 설정
  .github/workflows/test-link-deploy.yml
Labels: 🍀 지원, 배포

#417 [FIX] 모달 항상 중앙에 뜨도록 수정
  src/components/common/BtnTaskContainer.tsx
  src/components/common/StagingArea/StagingArea.tsx
  src/components/common/StagingArea/StagingAreaTaskContainer.tsx
  src/components/common/fullCalendar/FullCalendarBox.tsx
  src/components/common/v2/dropdown/TimeDropdown.tsx
  src/components/common/v2/modal/MainSettingModal.tsx
  src/components/common/v2/taskBox/Todo.tsx
  src/components/targetArea/FilterSection.tsx
  src/components/targetArea/TargetArea.tsx
  src/components/targetArea/TargetTaskSection.tsx
  src/pages/Today.tsx
  src/stories/Common/Button/Todo.stories.tsx
  src/stories/modal/MainSettingModal.stories.ts
Labels: 🏰 성희, v2

#425 [CHORE] 할 일 입력 글자 수 제한
  src/components/common/v2/TextBox/DumpingAreaBtn.tsx
Labels: 😻 승연
